# Device
device:
  gpus: (0,)
  workers_per_gpu: 8
  batchsize_per_gpu: 32
  precision: 16

save_dir: './exp'

# Model
model:
  network:
    name: DDRNet23_slim
    output_dim: 2
    augment: False
  loss:
    name: OhemCrossEntropyLoss

# Data
train_dataset:
  name: CustomDataset
  txt_path: '/project/datasets/expressage/train.txt'
  num_classes: 2
  img_suffixes: ['.jpg']
  mask_suffixes: ['.png']
  ignore_index: 255
  transforms:
    - op: RandomResizedCrop
      size: [576, 1024]
    - op: RandomAutocontrast
    - op: RandomHorizontalFlip
    - op: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  name: CustomDataset
  txt_path: '/project/datasets/expressage/val.txt'
  num_classes: 2
  img_suffixes: ['.jpg']
  mask_suffixes: ['.png']
  ignore_index: 255
  transforms:
    - op: Resize
      size: [576, 1024]
    - op: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Schedule
schedule:
  optimizer:
    name: SGD
    lr: 0.01
    weight_decay: 0.0005
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  resume: False
  total_epochs: 300
  val_intervals: 1

evaluator:
  name: SegmentEvaluator
  metric_key: miou

log:
  interval: 10