# Device
device:
  gpus: (0,)
  workers_per_gpu: 8
  batchsize_per_gpu: 32
  precision: 16

save_dir: './exp'

# Model
model:
  network:
    name: DDRNet23_slim
    output_dim: 2
    augment: True
    pretrained: /project/DDRNet23s_imagenet.pth
  loss:
    name: ComposeLoss
    losses: 
      - name: CrossEntropyLoss
        ignore_label: 255
      - name: OhemCrossEntropyLoss
        ignore_label: 255
        thresh: 0.9
        min_kept: 131072
    coef: [1.0, 0.4]
    indexes: [[0, 0, 0], [1, 1, 0]]

# Data
train_dataset:
  name: CustomDataset
  txt_path: '/project/datasets/expressage/train.txt'
  num_classes: 2
  img_suffixes: ['.jpg']
  mask_suffixes: ['.png']
  ignore_index: 255
  transforms:
    - op: RandomResizedCrop
      size: [576, 1024]
    - op: RandomAutocontrast
    - op: RandomHorizontalFlip
    - op: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  name: CustomDataset
  txt_path: '/project/datasets/expressage/val.txt'
  num_classes: 2
  img_suffixes: ['.jpg']
  mask_suffixes: ['.png']
  ignore_index: 255
  transforms:
    - op: Resize
      size: [576, 1024]
    - op: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Schedule
schedule:
  optimizer:
    # name: AdamW
    # lr: 0.01
    # weight_decay: 0.0005
    name: SGD
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.9
  warmup:
    name: linear
    steps: 300
    ratio: 0.001
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.0005
  resume: False
  total_epochs: 300
  val_intervals: 10

evaluator:
  name: ComposeEvaluator
  evals:
    - name: SegmentEvaluator
      metric_key: miou
    - name: SegmentEvaluator
      metric_key: miou
  indexes: [[0, 0, 0], [1, 1, 0]]
  metric_index: 1

log:
  interval: 10